App\Entity\Libro:
  attributes:
      id:
        groups: ['libro']
      title:
        groups: ['libro']
      image:
        groups: ['libro']
      categories:
        groups: ['libro']
      
      

